version: 2.1
orbs:
  node: circleci/node@1.1.6
  sonarcloud: sonarsource/sonarcloud@1.0.2
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: npm run push-coverage
            - sonarcloud/scan
workflows:
    build-and-test:
      context: SonarCloud
      jobs:
        - build-and-test
